import Head from "next/head";
import { AiFillPlusCircle, AiFillMinusCircle } from "react-icons/ai";

export default function Home() {
  return (
    <div className="body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font px-10">
        <div className="container py-12 mx-auto">
          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center items-start justify-around">
            <h1 className="text-xl xl:text-6xl font-medium title-font text-gray-900">
              Build your <br />
              <span className="font-extrabold">Dream House</span> into reality !
            </h1>
            <p className="w-1/3 p-16 text-xl">
              Auctor neque vitae tempus quam pellentesque nec nam aliquam sem et
              tortor consequat id porta.
            </p>
          </div>
          {/* ----Hero-Img---- */}
          <div className="image relative">
            {/* <div className="top-0 curve w-full h-10 bg-white absolute rounded-[0%_0%_50%_50%]"></div>
            <img src="/heroImg.jpg" className="w-full h-96 object-cover" />
          <div className="bottom-0 curve w-full h-10 bg-white absolute rounded-[50%_50%_0%_0%]"></div> */}
            <div className="image_curve w-[90rem] h-[30rem]">
              <img src="/heroImg.jpg" className="w-full object-cover" />
            </div>
          </div>
          {/* ----Hero-Img---- */}
        </div>
      </section>

      {/* ----Statistics---- */}
      <section className="my-10 px-16">
        <div className="grid grid-cols-2">
          <div className="flex flex-col justify-center">
            <h2 className="text-6xl text-gray-700">Trusted Quality</h2>
            <p className="w-1/2 text-xl mt-5 text-gray-600">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam
            </p>
          </div>
          <div className="bg-gray-100 flex items-center justify-center py-10">
            <div className="flex flex-col rounded-lg px-4 py-8 text-center mx-5">
              <dt className="order-last text-lg font-medium text-gray-500">
                Projects
              </dt>

              <dd className="text-4xl font-extrabold text-yellow-600 md:text-5xl">
                500+
              </dd>
            </div>
            <div className="flex flex-col rounded-lg px-4 py-8 text-center mx-5">
              <dt className="order-last text-lg font-medium text-gray-500">
                Customers
              </dt>

              <dd className="text-4xl font-extrabold text-yellow-600 md:text-5xl">
                23k+
              </dd>
            </div>
            <div className="flex flex-col rounded-lg px-4 py-8 text-center mx-5">
              <dt className="order-last text-lg font-medium text-gray-500">
                Reviews
              </dt>

              <dd className="text-4xl font-extrabold text-yellow-600 md:text-5xl">
                100k+
              </dd>
            </div>
          </div>
        </div>
      </section>
      {/* ----Statistics---- */}

      {/* ----SkillSets---- */}
      <section>
        <div className="mx-auto max-w-screen-2xl px-4 py-16 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:h-screen lg:grid-cols-2">
            <div className="relative z-10 lg:py-16">
              <div className="relative h-64 sm:h-80 lg:h-full">
                <img
                  alt="House"
                  src="https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"
                  className="absolute inset-0 h-full w-full object-cover"
                />
              </div>
            </div>

            <div className="relative flex items-center bg-gray-100">
              <span className="hidden lg:absolute lg:inset-y-0 lg:-left-16 lg:block lg:w-16 lg:bg-gray-100"></span>

              <div className="p-8 sm:p-16 lg:p-24">
                <h2 className="text-2xl font-bold sm:text-5xl">
                  Build with mature skills to construct a building
                </h2>

                <p className="mt-4 text-gray-600">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Aliquid, molestiae! Quidem est esse numquam odio deleniti,
                  beatae, magni dolores provident quaerat totam eos, aperiam
                  architecto eius quis quibusdam fugiat dicta.
                </p>

                <a
                  href="#"
                  className="mt-8 inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 transition ease-out duration-300 focus:outline-none focus:ring active:text-indigo-500"
                >
                  Contact Us
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* ----SkillSets---- */}

      {/* ----Projects---- */}
      <section className="px-10 mb-10">
        <div className="flex my-10 flex-col text-center">
          <h2 className="text-5xl text-gray-700">
            The last big project we worked on
          </h2>
          <div className="mt-3">
            <span className="inline-block w-40 h-1 bg-blue-500 rounded-full"></span>
            <span className="inline-block w-3 h-1 ml-1 bg-blue-500 rounded-full"></span>
            <span className="inline-block w-1 h-1 ml-1 bg-blue-500 rounded-full"></span>
          </div>
        </div>
        <div
          id="carouselDarkVariant"
          className="carousel slide carousel-fade carousel-dark relative"
          data-bs-ride="carousel"
        >
          {/* <!-- Indicators --> */}
          <div className="carousel-indicators absolute right-0 bottom-0 left-0 flex justify-center p-0 mb-4">
            <button
              data-bs-target="#carouselDarkVariant"
              data-bs-slide-to="0"
              className="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              data-bs-target="#carouselDarkVariant"
              data-bs-slide-to="1"
              aria-label="Slide 1"
            ></button>
            <button
              data-bs-target="#carouselDarkVariant"
              data-bs-slide-to="2"
              aria-label="Slide 1"
            ></button>
          </div>

          {/* <!-- Inner --> */}
          <div className="carousel-inner relative w-full overflow-hidden">
            {/* <!-- Single item --> */}
            <div className="carousel-item active relative float-left w-full">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(19).webp"
                className="block w-full"
                alt="Motorbike Smoke"
              />
              <div className="carousel-caption hidden md:block absolute text-center">
                <h5 className="text-xl">First slide label</h5>
                <p>
                  Some representative placeholder content for the first slide.
                </p>
              </div>
            </div>

            {/* <!-- Single item --> */}
            <div className="carousel-item relative float-left w-full">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(35).webp"
                className="block w-full"
                alt="Mountaintop"
              />
              <div className="carousel-caption hidden md:block absolute text-center">
                <h5 className="text-xl">Second slide label</h5>
                <p>
                  Some representative placeholder content for the second slide.
                </p>
              </div>
            </div>

            {/* <!-- Single item --> */}
            <div className="carousel-item relative float-left w-full">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(40).webp"
                className="block w-full"
                alt="Woman Reading a Book"
              />
              <div className="carousel-caption hidden md:block absolute text-center">
                <h5 className="text-xl">Third slide label</h5>
                <p>
                  Some representative placeholder content for the third slide.
                </p>
              </div>
            </div>
          </div>
          {/* <!-- Inner --> */}

          {/* <!-- Controls --> */}
          <button
            className="carousel-control-prev absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline left-0"
            type="button"
            data-bs-target="#carouselDarkVariant"
            data-bs-slide="prev"
          >
            <span
              className="carousel-control-prev-icon inline-block bg-no-repeat"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Previous</span>
          </button>
          <button
            className="carousel-control-next absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline right-0"
            type="button"
            data-bs-target="#carouselDarkVariant"
            data-bs-slide="next"
          >
            <span
              className="carousel-control-next-icon inline-block bg-no-repeat"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Next</span>
          </button>
        </div>
      </section>
      {/* ----Projects---- */}

      {/* ----FAQ's---- */}
      <section className="px-10 my-10">
        <div className="flex my-10 flex-col text-center">
          <h2 className="text-5xl text-gray-800">
            Find the answers you need !
          </h2>
          <div className="mt-3">
            <span className="inline-block w-40 h-1 bg-blue-500 rounded-full"></span>
            <span className="inline-block w-3 h-1 ml-1 bg-blue-500 rounded-full"></span>
            <span className="inline-block w-1 h-1 ml-1 bg-blue-500 rounded-full"></span>
          </div>
        </div>
        <div className="space-y-4">
          <details
            className="group rounded-lg border border-black p-6 [&_summary::-webkit-details-marker]:hidden"
            open
          >
            <summary className="flex items-center justify-between cursor-pointer">
              <h3 className="font-medium text-gray-700 text-4xl">
                Lorem ipsum dolor sit amet consectetur adipisicing?
              </h3>

              <span className="relative ml-1.5 h-5 w-5 flex-shrink-0">
                <AiFillPlusCircle className="absolute text-3xl opacity-100 group-open:opacity-0" />
                <AiFillMinusCircle className="text-3xl opacity-0 group-open:opacity-100" />
              </span>
            </summary>

            <p className="mt-4 leading-relaxed text-gray-600">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab hic
              veritatis molestias culpa in, recusandae laboriosam neque aliquid
              libero nesciunt voluptate dicta quo officiis explicabo
              consequuntur distinctio corporis earum similique!
            </p>
          </details>

          <details className="group rounded-lg border border-black p-6 [&_summary::-webkit-details-marker]:hidden">
            <summary className="flex items-center justify-between cursor-pointer">
              <h2 className="font-medium text-gray-700 text-4xl">
                Lorem ipsum dolor sit amet consectetur adipisicing?
              </h2>

              <span className="relative ml-1.5 h-5 w-5 flex-shrink-0">
                <AiFillPlusCircle className="absolute text-3xl opacity-100 group-open:opacity-0" />
                <AiFillMinusCircle className="text-3xl opacity-0 group-open:opacity-100" />
              </span>
            </summary>

            <p className="mt-4 leading-relaxed text-gray-700">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab hic
              veritatis molestias culpa in, recusandae laboriosam neque aliquid
              libero nesciunt voluptate dicta quo officiis explicabo
              consequuntur distinctio corporis earum similique!
            </p>
          </details>

          <details className="group rounded-lg border border-black p-6 [&_summary::-webkit-details-marker]:hidden">
            <summary className="flex items-center justify-between cursor-pointer">
              <h2 className="font-medium text-gray-700 text-4xl">
                Lorem ipsum dolor sit amet consectetur adipisicing?
              </h2>

              <span className="relative ml-1.5 h-5 w-5 flex-shrink-0">
                <AiFillPlusCircle className="absolute text-3xl opacity-100 group-open:opacity-0" />
                <AiFillMinusCircle className="text-3xl opacity-0 group-open:opacity-100" />
              </span>
            </summary>

            <p className="mt-4 leading-relaxed text-gray-700">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab hic
              veritatis molestias culpa in, recusandae laboriosam neque aliquid
              libero nesciunt voluptate dicta quo officiis explicabo
              consequuntur distinctio corporis earum similique!
            </p>
          </details>
        </div>
      </section>
      {/* ----FAQ's---- */}
    </div>
  );
}
