import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container py-24 mx-auto">
          <div className="px-10 flex flex-col sm:flex-row sm:items-center items-start justify-around mx-auto">
            <h1 className="sm:pr-7 text-2xl xl:text-7xl font-medium title-font text-gray-900">
              Build your <br /> <span className="font-extrabold">Dream House</span> into reality !
            </h1>
            <p className="w-1/3">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore
              quibusdam maxime maiores, impedit eaque animi nemo, quod veritatis
              at minus magni earum fuga. Voluptatem tempora voluptas quaerat,
              nihil non ullam.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
